In [29]:
D1="My dog is so lovely"
D2="furry puppy always looks lovely"
Corpus= [D1,D2]
Corpus

['My dog is so lovely', 'furry puppy always looks lovely']

In [7]:
# Bag of Words
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
#instantiate CountVectorizer()# CountVectorizer to count the number of words (term frequency)
cv = CountVectorizer() 
#this steps generates word counts for the words in your docs and return term-document matrix.
X = cv.fit_transform(Corpus).toarray()
print(cv.get_feature_names())
print("BOW Matrix:-")
pd.DataFrame(X, columns=cv.get_feature_names())

['always', 'dog', 'furry', 'is', 'looks', 'lovely', 'my', 'puppy', 'so']
BOW Matrix:-

   always  dog  furry  is  looks  lovely  my  puppy  so
0       0    1      0   1      0       1   1      0   1
1       1    0      1   0      1       1   0      1   0

In [8]:
from sklearn.feature_extraction.text import TfidfTransformer
cv_tfidf = TfidfTransformer(smooth_idf=True,norm=None)
X_tfidf = cv_tfidf.fit_transform(X).toarray()
pd.DataFrame(X_tfidf, columns=cv.get_feature_names())

,always,dog,furry,is,looks,lovely,my,puppy,so
0,0.000000,1.405465,0.000000,1.405465,0.000000,1.0,1.405465,0.000000,1.405465
1,1.405465,0.000000,1.405465,0.000000,1.405465,1.0,0.000000,1.405465,0.000000

Ref: https://github.com/scikit-learn/scikit-learn/blob/b194674c42d54b26137a456c510c5fdba1ba23e0/sklearn/feature_extraction/text.py#L820
Ref : C.D. Manning, P. Raghavan and H. Sch√ºtze  (2008).Introduction to Information Retrieval. Cambridge University Press, pp. 118-120.
https://nlp.stanford.edu/IR-book/pdf/irbookprint.pdf

### TfidfTransformer(norm='l2', use_idf=True, smooth_idf=True, sublinear_tf=False)

Parameters
    ----------
    norm : 'l1', 'l2' or None, optional (default='l2')
        Each output row will have unit norm, either:
        * 'l2': Sum of squares of vector elements is 1. The cosine
        similarity between two vectors is their dot product when l2 norm has
        been applied.
        * 'l1': Sum of absolute values of vector elements is 1.
        See :func:`preprocessing.normalize`
    use_idf : boolean (default=True)
        Enable inverse-document-frequency reweighting.
    smooth_idf : boolean (default=True)
        Smooth idf weights by adding one to document frequencies, as if an
        extra document was seen containing every term in the collection
        exactly once. Prevents zero divisions.
    sublinear_tf : boolean (default=False)
        Apply sublinear tf scaling, i.e. replace tf with 1 + log(tf).
    Attributes
    ----------
    idf_ : array, shape (n_features)
        The inverse document frequency (IDF) vector; only defined
        if  ``use_idf`` is True.

TfidfVectorizer(input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, 
preprocessor=None, tokenizer=None, analyzer='word', stop_words=None, token_pattern='(?u)\b\w\w+\b', ngram_range=(1, 1), 
max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.float64'>, norm='l2', 
use_idf=True, smooth_idf=True, sublinear_tf=False)

In [33]:
D1="My dog is so lovely"
D2="furry puppy always looks lovely"
Corpus= [D1,D2]
# new TF-IDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
# idf(t) = log [ n+1 / df(t)+1 ] + 1
#Tf is ‚Äún‚Äù (natural) by default, ‚Äúl‚Äù (logarithmic) when sublinear_tf=True. 
#Idf is ‚Äút‚Äù when use_idf is given, ‚Äún‚Äù (none) otherwise. Normalization is ‚Äúc‚Äù (cosine) when norm='l2', ‚Äún‚Äù (none) when norm=None.
cv_tfidf = TfidfVectorizer(norm=None)
X_tfidf = cv_tfidf.fit_transform(Corpus).toarray()
pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names())

,always,dog,furry,is,looks,lovely,my,puppy,so
0,0.000000,1.405465,0.000000,1.405465,0.000000,1.0,1.405465,0.000000,1.405465
1,1.405465,0.000000,1.405465,0.000000,1.405465,1.0,0.000000,1.405465,0.000000

In [32]:
# idf(t) = log [ n / df(t) ] + 1
cv_tfidf = TfidfVectorizer(smooth_idf=False,norm=None)
X_tfidf = cv_tfidf.fit_transform(Corpus).toarray()
pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names())

,always,dog,furry,is,looks,lovely,my,puppy,so
0,0.000000,1.693147,0.000000,1.693147,0.000000,1.0,1.693147,0.000000,1.693147
1,1.693147,0.000000,1.693147,0.000000,1.693147,1.0,0.000000,1.693147,0.000000

In [34]:
# idf(t) = log [ n / df(t) ] + 1 # After normalization
cv_tfidf = TfidfVectorizer(smooth_idf=False)
X_tfidf = cv_tfidf.fit_transform(Corpus).toarray()
pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names())

,always,dog,furry,is,looks,lovely,my,puppy,so
0,0.000000,0.479528,0.000000,0.479528,0.000000,0.283217,0.479528,0.000000,0.479528
1,0.479528,0.000000,0.479528,0.000000,0.479528,0.283217,0.000000,0.479528,0.000000